Pcf 67 api ad list
frontend-park-mail-ru/2023_2_PCF pull request #6
Opened 2023-10-06 12:19 UTC by BincomAD

2023-10-06 13:16 UTC, SergTyapkin requested changes

2023-10-06 13:16 UTC, SergTyapkin commented on public/components/list/list.hbs
> +                    <img src="../../static/img/free-icon-people-3633274.png" alt="Иконка">
alt нужен не для галочки. По нему должно быть понятно, что это за картинка, для средств чтения с экрана (для слабовидящих)

2023-10-06 13:16 UTC, SergTyapkin commented on public/components/list/list.js
> +    userAds: null,
`userAds: userAds,`

2023-10-06 13:16 UTC, SergTyapkin commented on public/components/list/list.js
> +           context.userAds = userAds
```JS
userAds.length = 0;
userAds.push(...data);
```

Чтобы не происходила перезапись ссылки на массив. Тогда у вас в контексте всегда будет лежать тот же массив

2023-10-06 13:16 UTC, SergTyapkin commented on public/components/list/list.js
> +        document.getElementById("1").addEventListener("click", () => {
Давайте у элементов будут `id="ads-button-1"`, а не просто цифра

2023-10-06 13:16 UTC, SergTyapkin commented on public/components/list/list.precompiled.js
Почему в коммите лежит файл из `.gitignore`?

2023-10-06 13:16 UTC, SergTyapkin commented on public/components/login/login.hbs
> +        <input type="email" placeholder="Логин" id="login">
Отступы

2023-10-06 13:16 UTC, SergTyapkin commented on public/components/login/login.js
> +import { Api } from "../../modules/api.js";
Почему не сделать `export default` и в API, и в Validate?

2023-10-18 06:35 UTC, almkuznetsov commented on public/components/list/list.js
> +        document.getElementById("1").addEventListener("click", () => {
Это очень временное решение, потом вообще это уберем, да

2023-10-18 06:39 UTC, almkuznetsov commented on public/components/list/list.precompiled.js
precompiled нет в гитигноре, они только в eslintignore, т.к. он их не обрабатывает. Стоит ли добавить в гитигнор тоже?

2023-10-31 07:43 UTC, almkuznetsov commented
Договорились с Сережей, что он будет смотреть ПРы в мейн. Чтобы работа не стояла сольем эту ветку в девелоп новым ПРом

2023-10-31 07:43 UTC, closed without merging